-- ==============================================================================
-- Quantiq Prime (http://quantiqprime.com) - Production Crypto Deposit Schema
-- Database: MySQL 8.0+ / MariaDB (InnoDB Engine with ACID Transactions)
-- ==============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- 1. Users Table (Core investor balance store)
CREATE TABLE IF NOT EXISTS `users` (
  `id` VARCHAR(64) NOT NULL,
  `email` VARCHAR(191) NOT NULL,
  `full_name` VARCHAR(191) NULL,
  `balance_usd` DECIMAL(18, 4) NOT NULL DEFAULT 0.0000,
  `balance_kes` DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
  `total_deposited_usd` DECIMAL(18, 4) NOT NULL DEFAULT 0.0000,
  `status` ENUM('active', 'suspended', 'pending') NOT NULL DEFAULT 'active',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_users_email` (`email`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 2. Crypto Deposits Table (Tracks every live mainnet payment)
CREATE TABLE IF NOT EXISTS `crypto_deposits` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(64) NOT NULL,
  `payment_id` VARCHAR(100) NOT NULL COMMENT 'NOWPayments unique payment ID',
  `order_id` VARCHAR(100) NOT NULL COMMENT 'Internal unique order reference',
  `price_amount` DECIMAL(18, 4) NOT NULL COMMENT 'Requested fiat/USD amount',
  `price_currency` VARCHAR(10) NOT NULL DEFAULT 'USD',
  `pay_amount` DECIMAL(28, 12) NOT NULL COMMENT 'Exact crypto amount expected',
  `actually_paid` DECIMAL(28, 12) NOT NULL DEFAULT 0.000000000000 COMMENT 'Actual crypto amount received on-chain',
  `pay_currency` VARCHAR(20) NOT NULL COMMENT 'e.g. usdtbsc, btc, usdttrc20',
  `pay_address` VARCHAR(191) NOT NULL COMMENT 'Mainnet on-chain deposit address generated by NOWPayments',
  `pay_extra_id` VARCHAR(191) NULL COMMENT 'Memo/tag if required (e.g. XRP/EOS)',
  `payment_status` VARCHAR(50) NOT NULL DEFAULT 'waiting' COMMENT 'waiting, confirming, confirmed, finished, failed, expired, partially_paid',
  `credited` TINYINT(1) NOT NULL DEFAULT 0 COMMENT '1 = balance credited to user, 0 = pending/uncredited',
  `credited_amount_usd` DECIMAL(18, 4) NOT NULL DEFAULT 0.0000,
  `credited_at` TIMESTAMP NULL DEFAULT NULL,
  `tx_hash` VARCHAR(191) NULL COMMENT 'On-chain transaction hash from network',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_payment_id` (`payment_id`),
  UNIQUE KEY `idx_order_id` (`order_id`),
  KEY `idx_user_deposits` (`user_id`, `payment_status`),
  KEY `idx_status_credited` (`payment_status`, `credited`),
  CONSTRAINT `fk_crypto_deposits_user` FOREIGN KEY (`user_id`) REFERENCES `users` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 3. Webhook Audit Logs Table (Full IPN signature & payload audit trail)
CREATE TABLE IF NOT EXISTS `crypto_webhook_logs` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `payment_id` VARCHAR(100) NULL,
  `event_status` VARCHAR(50) NULL,
  `signature_received` VARCHAR(255) NULL,
  `signature_verified` TINYINT(1) NOT NULL DEFAULT 0,
  `payload_json` LONGTEXT NOT NULL,
  `remote_ip` VARCHAR(45) NULL,
  `error_message` VARCHAR(255) NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_logs_payment` (`payment_id`),
  KEY `idx_logs_created` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;
